name: Clang Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Clang
        run: |
          sudo apt-get install -y clang-format

      - name: Run clang-format
        run: |
          clang-format -i src/**/*.cpp src/**/*.h

      - name: Check for formatting issues
        run: |
          git diff --exit-code || echo "Code is not formatted. Please run clang-format."
