name: Run perft tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  perft-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y build-essential
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install make
          fi

      - name: Build Sonic
        working-directory: src
        run: make

      - name: Run perft tests
        working-directory: src
        run: |
          echo -e "perft\nquit" | ./sonic
