name: Run perft tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  perft-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update || brew update
          sudo apt-get install -y build-essential || brew install make

      - name: Build Sonic
        working-directory: Sonic/src
        run: make

      - name: Run perft tests
        working-directory: Sonic/src
        run: |
          echo -e "perft\nquit" | ./sonic
